#!/data/data/com.termux/files/usr/bin/bash 

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
W="$(printf '\033[1;37m')"


if [ ! -d "/data/data/com.termux/files/home/storage" ]; then
    echo ${G}"Please allow storage permission"${W}
    termux-setup-storage
fi
clear 
echo ${G}"Please put in your youtube URL for download"${W}
read URL
echo ${G}"Checking URL, please wait... "
sleep 1 
if [[ $URL != http?(s)://youtu* ]]; then
    echo ${R}"Invalid input"
    exit 1
fi 

echo ""
echo ${G}"Default video format is mp4"
sleep 1 
echo ""
echo ${G}"Playlist will be saved in Downloads directory "
echo ${G}"Please put in the playlist name you want to be saved"${W}
read playlist_name 
echo 
sleep 1 
echo ${G}"Start downloading ...."
echo ${G}"Please wait ...."${W}
yt-dlp -S ext:mp4:m4a "$URL" --yes-playlist --embed-chapters -o "storage/shared/Download/$playlist_name"
sleep 1 
echo ""
echo ${G}"Finish Download!"
echo ${G}"For more usage, please refer to "
echo ${W}" https://github.com/yt-dlp/yt-dlp"
